### PR TITLE
apis/core/v1: Register Event and EventList

### PR DESCRIPTION
**Pull request by keegancsmith**

### CODE REVIEW

**Comment by keegancsmith** [comment]
I see the package I modified is just a codemod of an upstream pkg. Any idea why events is not registered upstream? It is a valid resource to interact with.

**Comment by msharbaji** [comment]
@ericchiang  Can you please check if you can merge this request?

I have tried to use `events/v1beta1` but didn't work getting page not found, and for `core/v1` is wroking

**Comment by ericchiang** [comment]
This file is generated, you'll need to modify this instead https://github.com/ericchiang/k8s/blob/master/scripts/register.go

As a workaround, you can just register this in your own code:

```
func init() {
    k8s.Register("", "v1", "events", true, &v1.Event{})
    k8s.RegisterList("", "v1", "events", true, &v1.EventList{})
}
```

**Comment by ericchiang** [comment]
#118

**Pull request closed without merging**
